terratest (#1)
terratest

diff --git a/scripts/terratest b/scripts/terratest
--- a/scripts/terratest
+++ b/scripts/terratest
@@ -12,15 +12,14 @@ set -eu -o pipefail
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 readonly DIR
 
-if ! command -v terraform-docs > /dev/null; then
-  echo "terraform-docs is missing."
+if ! command -v go > /dev/null; then
+  echo "go is missing."
   exit 1
 fi
 
-pushd "${DIR}/.." > /dev/null
-terraform-docs markdown . > README.md
-echo "<!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->" >> TMP_README.md
-cat README.md >> TMP_README.md
-echo "<!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->" >> TMP_README.md
-mv TMP_README.md README.md
-popd  > /dev/null
+if ! command -v terraform > /dev/null; then
+  echo "terraform is missing."
+  exit 1
+fi
+
+go test -short -count 1 -timeout 15m "${DIR}/../test/..."
